apiVersion: v1
kind: Secret
metadata:
  name: sysdigcloud-pull-secret
  namespace: sysdigcloud
data:
  .dockerconfigjson: 
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdigcloud-config
  namespace: sysdigcloud
data:
  #License
  sysdigcloud.license: ""
  #endpoints
  elasticsearch.url: http://sdc-elasticsearch
  redis.endpoint: sdc-redis
  cassandra.endpoint: sdc-cassandra
  mysql.endpoint: sdc-mysql
  collector.endpoint: sdc-collector
  collector.port: "6443"
  api.url: https://sdc-api:443
  #passwords
  sysdigcloud.default.user: test@sysdig.com
  sysdigcloud.default.user.password: test
  cassandra.user: ""
  cassandra.password: ""
  redis.password: ""
  mysql.user: admin
  mysql.password: password
  mysql.root.password: password
  #jvm options
  cassandra.jvm.options: ""
  elasticsearch.jvm.options: ""
  sysdigcloud.jvm.options: ""
  #Cassandra
  cassandra.secure: "false"
  cassandra.ssl.enabled: "false"
  cassandra.ssl.ciphers: ""
  cassandra.port: "9042"
  cassandra.replication.factor: "3"
  sysdigcloud.captures.cassandra.storage: "true"
  #smtp
  smtp.server: ""
  smtp.server.port: "25"
  smtp.user: ""
  smtp.password: ""
  smtp.tls: "false"
  smtp.ssl: "false"
  smtp.from.address: ""
  #logging
  sysdigcloud.logging.stdout: "false"
  #Auth and LDAP
  sysdigcloud.oauth.allowed.domains.list: ""
  sysdigcloud.google.oauth.client.id: ""
  sysdigcloud.google.oauth.client.secret: ""
  sysdigcloud.ldap.enabled: "false"
  sysdigcloud.ldap.endpoint: ""
  sysdigcloud.ldap.manager.dn: ""
  sysdigcloud.ldap.manager.password: ""
  sysdigcloud.ldap.root.dn: ""
  sysdigcloud.ldap.user.search.base: ""
  sysdigcloud.ldap.user.search.filter: ""
  sysdigcloud.ldap.group.search.base: ""
  sysdigcloud.ldap.group.search.filter: ""
  sysdigcloud.ldap.group.membership.filter: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdigcloud-mysql-config
  namespace: sysdigcloud
  labels:
    app: sysdigcloud
data:
  # Required: MySQL endpoint DNS/IP. If MySQL is deployed as a Kubernetes service, 
  # this will be the service name. If using an external database, put the proper address
  mysql.endpoint: sdc-mysql
  # Required: MySQL user
  mysql.user: admin
  # Required: MySQL password
  mysql.password: password
  mysql.root.password: password
  mysql.replication.user: repluser
  mysql.replication.password: password
  master.cnf: |-
    [client]
    port   = 3306
    socket   = /var/run/mysqld/mysqld.sock
    default-character-set=utf8

    [mysql]
    default-character-set=utf8
    [mysqld_safe]
    pid-file = /var/run/mysqld/mysqld.pid
    socket   = /var/run/mysqld/mysqld.sock
    nice   = 0
    [mysqld]
    user   = mysql
    pid-file = /var/run/mysqld/mysqld.pid
    socket   = /var/run/mysqld/mysqld.sock
    port   = 3306
    basedir    = /usr
    datadir    = /var/lib/mysql
    tmpdir   = /tmp
    lc-messages-dir  = /usr/share/mysql
    explicit_defaults_for_timestamp
    collation-server = utf8_unicode_ci
    init-connect='SET NAMES utf8'
    character-set-server = utf8
    log-error  = /var/log/mysql/error.log
    # Recommended in standard MySQL setup
    sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links=0
    # Replicate to slaves
    log-bin=sysdigcloud-mysql-0-bin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdigcloud-mysql-config-slave
  namespace: sysdigcloud
  labels:
    app: sysdigcloud-mysql-slave
data:
  mysql.endpoint: sdc-mysql
  mysql.user: admin
  mysql.password: password
  mysql.root.password: password
  mysql.replication.user: repluser
  mysql.replication.password: password
  slave.cnf: |-
    [client]
    port   = 3306
    socket   = /var/run/mysqld/mysqld.sock
    default-character-set=utf8

    [mysql]
    default-character-set=utf8
    [mysqld_safe]
    pid-file = /var/run/mysqld/mysqld.pid
    socket   = /var/run/mysqld/mysqld.sock
    nice   = 0
    [mysqld]
    user   = mysql
    pid-file = /var/run/mysqld/mysqld.pid
    socket   = /var/run/mysqld/mysqld.sock
    port   = 3306
    basedir    = /usr
    datadir    = /var/lib/mysql
    tmpdir   = /tmp
    lc-messages-dir  = /usr/share/mysql
    explicit_defaults_for_timestamp
    collation-server = utf8_unicode_ci
    init-connect='SET NAMES utf8'
    character-set-server = utf8
    log-error  = /var/log/mysql/error.log
    # Recommended in standard MySQL setup
    sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links=0
    # Writes from master only
    super-read-only
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdigcloud-redis-config
  namespace: sysdigcloud
  labels:
    app: sysdigcloud
    role: redis
data:
  redis.password: ""
  redis.conf: |+
    cluster-enabled no
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    cluster-migration-barrier 1
    appendonly yes
    protected-mode no
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdigcloud-redis-config-slave
  namespace: sysdigcloud
  labels:
    app: sysdigcloud
    role: redis-slave
data:
  redis.password: ""
  redis.conf: |+
    cluster-enabled no 
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    cluster-migration-barrier 1
    appendonly yes
    protected-mode no
    slaveof sdc-redis-0.sdc-redis.sysdigcloud.svc.cluster.local 6379

